server:
  port: 8888

spring:
  application:
    name: gateway-application
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: user-service-prod
          uri: http://www.baidu.com
          predicates:
            - Path=/**
            - Weight=user-service, 50
        - id: user-service-canary
          uri: https://www.oschina.net
          predicates:
            - Path=/**
            - Weight=user-service, 50   # 使用 Weight 匹配条件，设置不同的权重条件。其中，第一个参数为权重分组，需要配置成相同，一般和服务名相同即可；第二个参数为权重比例。

              # 第一，Spring Cloud 微服务在注册到注册中心时，需要在元数据中带上版本号。例如说，version = 1.0.0、version = 1.1.0。
              # 第二，Gateway 在 lb://serviceId 负载均衡选择请求的服务实例时，需要增加基于版本号的选择规则。