server:
  port: 8888

spring:
  application:
    name: gateway-application

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: oschina # 路由的编号
          uri: https://www.oschina.net # 路由的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/oschina
          filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
            - StripPrefix=1
      # 默认过滤器，对应 FilterDefinition 数组
      # 如果只想给指定路由配置过滤器，可以在 spring.cloud.gateway.routes[x].filters 配置项中，进行自定义设置。
      default-filters:
        - name: Auth  # 因为 Gateway 默认使用 XXXGatewayFilterFactory 的前缀 XXX 为名字，因此 AuthGatewayFilterFactory 就是 Auth。
          args:   # 过滤器的配置参数，对应 Map 类。这里我们设置 token-header-name 配置项为 access-token，表示从请求 Header access-token 获得认证 Token。
            token-header-name: access-token